import { Preset, AnimationSettings } from './types';

export const defaultSettings: AnimationSettings = {
  backgroundColor: '#0a0a0f',
  backgroundGradient: true,
  backgroundGradientColor: '#1a0a2e',
  geometryType: 'torusKnot',
  shapeCount: 1,
  shapeScale: 1,
  shapeColor: '#8b5cf6',
  shapeColor2: '#06b6d4',
  useGradientMaterial: true,
  wireframe: false,
  metalness: 0.8,
  roughness: 0.2,
  animationType: 'orbit',
  loopDuration: 4,
  speed: 1,
  amplitude: 1,
  spread: 2,
  frequency: 1,
  phaseOffset: 0,
  verticalAmplitude: 1,
  horizontalAmplitude: 1,
  cameraDistance: 6,
  cameraAutoRotate: false,
  cameraAutoRotateSpeed: 1,
  bloomEnabled: true,
  bloomIntensity: 0.5,
  motionBlurEnabled: false,
  motionBlurAmount: 0.5,
  // Render modes - ASCII
  asciiEnabled: false,
  asciiCharset: 'standard',
  asciiResolution: 60,
  asciiOpacity: 1,
  asciiBackgroundOpacity: 1,
  asciiTextColor: '#00ff00',
  asciiFontSize: 12,
  asciiFontWeight: 'bold',
  asciiInvert: false,
  asciiContrast: 1.2,
  asciiGamma: 1.0,
  asciiColorMode: true,
  asciiBrightnessBoost: 1.0,
  exportWidth: 1080,
  exportHeight: 1080,
  exportFps: 30,
  exportFormat: 'webm',
  exportQuality: 'excellent',
  exportLoopCount: 1,
  seamlessLoopVerification: true,
};

export const presets: Preset[] = [
  {
    id: 'cosmic-torus',
    name: 'Cosmic Torus',
    description: 'A glowing torus knot orbiting in space',
    thumbnail: '🌀',
    settings: {
      geometryType: 'torusKnot',
      shapeCount: 1,
      shapeColor: '#8b5cf6',
      shapeColor2: '#ec4899',
      animationType: 'orbit',
      loopDuration: 4,
      metalness: 0.9,
      roughness: 0.1,
      backgroundColor: '#05050f',
      backgroundGradientColor: '#0f0520',
    },
  },
  {
    id: 'sacred-geometry',
    name: 'Sacred Geometry',
    description: 'Breathing icosahedrons in harmony',
    thumbnail: '💎',
    settings: {
      geometryType: 'icosahedron',
      shapeCount: 5,
      shapeColor: '#f59e0b',
      shapeColor2: '#ef4444',
      animationType: 'breathe',
      loopDuration: 3,
      wireframe: true,
      metalness: 0.5,
      roughness: 0.5,
      amplitude: 1.2,
      spread: 3,
      backgroundColor: '#0a0505',
      backgroundGradientColor: '#1a0a05',
    },
  },
  {
    id: 'neon-spiral',
    name: 'Neon Spiral',
    description: 'Cubes spiraling into infinity',
    thumbnail: '🔮',
    settings: {
      geometryType: 'cube',
      shapeCount: 12,
      shapeScale: 0.6,
      shapeColor: '#06d6a0',
      shapeColor2: '#118ab2',
      animationType: 'spiral',
      loopDuration: 5,
      speed: 0.8,
      spread: 4,
      backgroundColor: '#020a08',
      backgroundGradientColor: '#051a15',
    },
  },
  {
    id: 'crystal-wave',
    name: 'Crystal Wave',
    description: 'Octahedrons riding a wave',
    thumbnail: '🌊',
    settings: {
      geometryType: 'octahedron',
      shapeCount: 8,
      shapeScale: 0.5,
      shapeColor: '#3b82f6',
      shapeColor2: '#a855f7',
      animationType: 'wave',
      loopDuration: 3,
      amplitude: 1.5,
      spread: 5,
      backgroundColor: '#050510',
      backgroundGradientColor: '#0a0a25',
    },
  },
  {
    id: 'supernova',
    name: 'Supernova',
    description: 'Shapes exploding and reforming',
    thumbnail: '💥',
    settings: {
      geometryType: 'tetrahedron',
      shapeCount: 16,
      shapeScale: 0.4,
      shapeColor: '#f97316',
      shapeColor2: '#eab308',
      animationType: 'explode',
      loopDuration: 4,
      amplitude: 2,
      spread: 1,
      backgroundColor: '#0a0500',
      backgroundGradientColor: '#1a0f00',
    },
  },
  {
    id: 'minimalist-sphere',
    name: 'Minimalist Sphere',
    description: 'Clean, elegant sphere animation',
    thumbnail: '⚪',
    settings: {
      geometryType: 'sphere',
      shapeCount: 1,
      shapeScale: 1.5,
      shapeColor: '#ffffff',
      shapeColor2: '#94a3b8',
      animationType: 'breathe',
      loopDuration: 3,
      metalness: 1,
      roughness: 0,
      wireframe: false,
      backgroundColor: '#0f172a',
      backgroundGradientColor: '#1e293b',
      bloomIntensity: 0.3,
    },
  },
  {
    id: 'matrix-cascade',
    name: 'Matrix Cascade',
    description: 'Shapes cascading like digital rain',
    thumbnail: '🟩',
    settings: {
      geometryType: 'cube',
      shapeCount: 20,
      shapeScale: 0.3,
      shapeColor: '#22c55e',
      shapeColor2: '#15803d',
      animationType: 'cascade',
      loopDuration: 4,
      speed: 1.2,
      spread: 5,
      wireframe: true,
      backgroundColor: '#000a00',
      backgroundGradientColor: '#001a00',
    },
  },
  {
    id: 'vortex-storm',
    name: 'Vortex Storm',
    description: 'A mesmerizing vortex of shapes',
    thumbnail: '🌪️',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 10,
      shapeScale: 0.5,
      shapeColor: '#e11d48',
      shapeColor2: '#7c3aed',
      animationType: 'vortex',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.5,
      spread: 3,
      backgroundColor: '#0a0005',
      backgroundGradientColor: '#15000a',
    },
  },
  {
    id: 'pendulum-zen',
    name: 'Pendulum Zen',
    description: 'Peaceful pendulum-like motion',
    thumbnail: '🕐',
    settings: {
      geometryType: 'cylinder',
      shapeCount: 7,
      shapeScale: 0.4,
      shapeColor: '#f0abfc',
      shapeColor2: '#c084fc',
      animationType: 'pendulum',
      loopDuration: 4,
      amplitude: 1.3,
      spread: 4,
      backgroundColor: '#0a0010',
      backgroundGradientColor: '#150020',
    },
  },
  {
    id: 'kaleidoscope-dream',
    name: 'Kaleidoscope',
    description: 'Mesmerizing kaleidoscope pattern',
    thumbnail: '🎭',
    settings: {
      geometryType: 'cone',
      shapeCount: 12,
      shapeScale: 0.5,
      shapeColor: '#fb923c',
      shapeColor2: '#f472b6',
      animationType: 'kaleidoscope',
      loopDuration: 6,
      speed: 0.8,
      spread: 3,
      backgroundColor: '#050005',
      backgroundGradientColor: '#100010',
    },
  },
  {
    id: 'ring-dance',
    name: 'Ring Dance',
    description: 'Elegant rings orbiting in harmony',
    thumbnail: '⭕',
    settings: {
      geometryType: 'ring',
      shapeCount: 5,
      shapeScale: 0.8,
      shapeColor: '#a78bfa',
      shapeColor2: '#60a5fa',
      animationType: 'wave',
      loopDuration: 4,
      amplitude: 1,
      spread: 3,
      backgroundColor: '#0a0015',
      backgroundGradientColor: '#1a0030',
    },
  },
  {
    id: 'pyramid-stack',
    name: 'Pyramid Stack',
    description: 'Pyramids stacking in mystical rhythm',
    thumbnail: '△',
    settings: {
      geometryType: 'pyramid',
      shapeCount: 8,
      shapeScale: 0.6,
      shapeColor: '#fbbf24',
      shapeColor2: '#f97316',
      animationType: 'explode',
      loopDuration: 5,
      amplitude: 2,
      spread: 2,
      backgroundColor: '#0a0500',
      backgroundGradientColor: '#1a0f00',
    },
  },
  {
    id: 'plane-cascade',
    name: 'Plane Cascade',
    description: 'Planes cascading in digital flow',
    thumbnail: '◻️',
    settings: {
      geometryType: 'plane',
      shapeCount: 12,
      shapeScale: 0.5,
      shapeColor: '#34d399',
      shapeColor2: '#10b981',
      animationType: 'cascade',
      loopDuration: 4,
      speed: 1,
      spread: 4,
      backgroundColor: '#000a05',
      backgroundGradientColor: '#001505',
    },
  },
  {
    id: 'prism-geometry',
    name: 'Prism Geometry',
    description: 'Crystalline prisms breathing in 3D',
    thumbnail: '🔷',
    settings: {
      geometryType: 'prism',
      shapeCount: 6,
      shapeScale: 0.7,
      shapeColor: '#c084fc',
      shapeColor2: '#e879f9',
      animationType: 'breathe',
      loopDuration: 3.5,
      amplitude: 1.5,
      spread: 3,
      metalness: 0.7,
      roughness: 0.3,
      backgroundColor: '#0a0010',
      backgroundGradientColor: '#150025',
    },
  },
  {
    id: 'sphere-trance',
    name: 'Sphere Trance',
    description: 'Hypnotic spiral of glowing spheres',
    thumbnail: '●',
    settings: {
      geometryType: 'sphere',
      shapeCount: 9,
      shapeScale: 0.6,
      shapeColor: '#ec4899',
      shapeColor2: '#f43f5e',
      animationType: 'spiral',
      loopDuration: 5,
      speed: 0.9,
      amplitude: 1.2,
      spread: 3.5,
      backgroundColor: '#05000a',
      backgroundGradientColor: '#0f0015',
    },
  },
  {
    id: 'morphing-abyss',
    name: 'Morphing Abyss',
    description: 'Shapes morph through dimensional space',
    thumbnail: '🌀',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 4,
      shapeScale: 1,
      shapeColor: '#7c3aed',
      shapeColor2: '#3b82f6',
      animationType: 'morph',
      loopDuration: 6,
      speed: 1,
      amplitude: 1.5,
      spread: 2.5,
      bloomIntensity: 0.7,
      backgroundColor: '#050010',
      backgroundGradientColor: '#0a001a',
    },
  },
  {
    id: 'cube-rotation',
    name: 'Cube Maze',
    description: 'Cubes rotating through infinite maze',
    thumbnail: '🎲',
    settings: {
      geometryType: 'cube',
      shapeCount: 15,
      shapeScale: 0.4,
      shapeColor: '#06d6a0',
      shapeColor2: '#13b0f5',
      animationType: 'kaleidoscope',
      loopDuration: 5,
      speed: 1,
      spread: 3,
      wireframe: true,
      backgroundColor: '#000805',
      backgroundGradientColor: '#001005',
    },
  },
  {
    id: 'zen-pendulum',
    name: 'Zen Pendulum',
    description: 'Peaceful swaying of prismatic forms',
    thumbnail: '⛩️',
    settings: {
      geometryType: 'prism',
      shapeCount: 5,
      shapeScale: 0.8,
      shapeColor: '#fca5a5',
      shapeColor2: '#fb7185',
      animationType: 'pendulum',
      loopDuration: 4,
      amplitude: 1.2,
      spread: 2.5,
      metalness: 0.5,
      roughness: 0.6,
      backgroundColor: '#0a0005',
      backgroundGradientColor: '#150a0a',
    },
  },
  {
    id: 'ascii-retro',
    name: 'ASCII Retro',
    description: 'Large, bold ASCII characters with retro styling',
    thumbnail: '💻',
    settings: {
      geometryType: 'cube',
      shapeCount: 12,
      shapeScale: 0.8,
      shapeColor: '#00ff00',
      shapeColor2: '#ffffff',
      animationType: 'orbit',
      loopDuration: 4,
      speed: 0.5,
      amplitude: 1,
      spread: 4,
      backgroundColor: '#000000',
      backgroundGradient: false,
      asciiEnabled: true,
      asciiCharset: 'blocks',
      asciiResolution: 80,
      asciiFontSize: 24,
      asciiFontWeight: 'bold',
      asciiOpacity: 1,
      asciiBackgroundOpacity: 1,
      asciiColorMode: true,
      asciiContrast: 1.5,
      asciiGamma: 0.8,
      asciiBrightnessBoost: 1.5,
      asciiInvert: false,
    },
  },
  {
    id: 'bounce-party',
    name: 'Bounce Party',
    description: 'Shapes bouncing in joyful rhythm',
    thumbnail: '🏀',
    settings: {
      geometryType: 'sphere',
      shapeCount: 8,
      shapeScale: 0.6,
      shapeColor: '#fbbf24',
      shapeColor2: '#f59e0b',
      animationType: 'bounce',
      loopDuration: 3,
      speed: 1.2,
      amplitude: 1.5,
      verticalAmplitude: 2,
      horizontalAmplitude: 1,
      spread: 4,
      frequency: 2,
      backgroundColor: '#0a0500',
      backgroundGradientColor: '#1a0f00',
    },
  },
  {
    id: 'twist-dream',
    name: 'Twist Dream',
    description: 'Twisting shapes in hypnotic motion',
    thumbnail: '🌀',
    settings: {
      geometryType: 'torusKnot',
      shapeCount: 3,
      shapeScale: 0.8,
      shapeColor: '#a855f7',
      shapeColor2: '#c084fc',
      animationType: 'twist',
      loopDuration: 4,
      speed: 0.9,
      amplitude: 1.2,
      verticalAmplitude: 1.5,
      horizontalAmplitude: 1.8,
      spread: 3,
      frequency: 1.5,
      backgroundColor: '#0a0010',
      backgroundGradientColor: '#150020',
    },
  },
  {
    id: 'pulse-wave',
    name: 'Pulse Wave',
    description: 'Pulsing cubes in wave formation',
    thumbnail: '💓',
    settings: {
      geometryType: 'cube',
      shapeCount: 10,
      shapeScale: 0.5,
      shapeColor: '#06b6d4',
      shapeColor2: '#0891b2',
      animationType: 'pulse',
      loopDuration: 3.5,
      speed: 1,
      amplitude: 1.8,
      verticalAmplitude: 1.2,
      horizontalAmplitude: 1.5,
      spread: 5,
      frequency: 2.5,
      backgroundColor: '#020a08',
      backgroundGradientColor: '#051a15',
    },
  },
  {
    id: 'figure8-flow',
    name: 'Figure 8 Flow',
    description: 'Elegant figure-8 motion patterns',
    thumbnail: '∞',
    settings: {
      geometryType: 'icosahedron',
      shapeCount: 6,
      shapeScale: 0.7,
      shapeColor: '#ec4899',
      shapeColor2: '#f97316',
      animationType: 'figure8',
      loopDuration: 5,
      speed: 0.8,
      amplitude: 1.3,
      verticalAmplitude: 1.6,
      horizontalAmplitude: 2,
      spread: 3.5,
      frequency: 1,
      backgroundColor: '#0a0005',
      backgroundGradientColor: '#1a000f',
    },
  },
  {
    id: 'helix-spiral',
    name: 'Helix Spiral',
    description: 'DNA-like helical motion',
    thumbnail: '🧬',
    settings: {
      geometryType: 'cylinder',
      shapeCount: 12,
      shapeScale: 0.4,
      shapeColor: '#10b981',
      shapeColor2: '#059669',
      animationType: 'helix',
      loopDuration: 6,
      speed: 1.1,
      amplitude: 1,
      verticalAmplitude: 2,
      horizontalAmplitude: 1.5,
      spread: 4,
      frequency: 3,
      backgroundColor: '#000a05',
      backgroundGradientColor: '#001505',
    },
  },
  {
    id: 'ripple-effect',
    name: 'Ripple Effect',
    description: 'Rippling waves of geometric shapes',
    thumbnail: '🌊',
    settings: {
      geometryType: 'plane',
      shapeCount: 15,
      shapeScale: 0.6,
      shapeColor: '#3b82f6',
      shapeColor2: '#1d4ed8',
      animationType: 'ripple',
      loopDuration: 4,
      speed: 1.3,
      amplitude: 1.5,
      verticalAmplitude: 2,
      horizontalAmplitude: 1,
      spread: 6,
      frequency: 2,
      backgroundColor: '#050510',
      backgroundGradientColor: '#0a0a25',
    },
  },
  {
    id: 'swirl-chaos',
    name: 'Swirl Chaos',
    description: 'Chaotic swirling motion',
    thumbnail: '🌪️',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 8,
      shapeScale: 0.5,
      shapeColor: '#ef4444',
      shapeColor2: '#dc2626',
      animationType: 'swirl',
      loopDuration: 4.5,
      speed: 1.4,
      amplitude: 1.7,
      verticalAmplitude: 1.8,
      horizontalAmplitude: 2,
      spread: 3.5,
      frequency: 1.8,
      backgroundColor: '#0a0000',
      backgroundGradientColor: '#1a0000',
    },
  },
];